version: '3.3'

services:
  postgresql:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: jazapp
      POSTGRES_USER: jazapp
      POSTGRES_PASSWORD: jazapp!98
    networks:
      lonczepsql:
        ipv4_address: 172.168.0.2
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

networks:
  lonczepsql:
    ipam:
      driver: default
      config:
        - subnet: 172.168.0.0/16